name: 'rs-clippy-check'
description: 'Run clippy and annotate the diff with errors and warnings'
author: 'clechasseur'
inputs:
  toolchain:
    description: Toolchain to use (without the `+` sign, ex. `nightly`)
    required: false
  args:
    description: Arguments for the cargo clippy command
    required: false
  use-cross:
    description: Use cross instead of cargo
    default: false
  working-directory:
    description: Directory where to perform cargo clippy command
    required: false
outputs:
  num-issues:
    description: When -D warnings is not passed and you want to still know how many issues clippy has found

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: paperclip
  color: black
